services:
  php:
    build:
      context: "../../../src/hatshop"      
    user: www-data:www-data
    restart: unless-stopped
    env_file: .env
    expose:
      - "80"
    networks:
      - hatshop-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "10080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
    networks:
      - hatshop-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    env_file: .env
    command: tunnel --no-autoupdate run --token $CLOUD_FLARE_TOKEN
    depends_on:
      - nginx
    networks:
      - hatshop-network

networks:
  hatshop-network:
    driver: bridge
