# HatShop Secrets - SOPS encrypted
# Encrypt with: sops encrypt --age age1mg4zlx7p736nnrp7glt7gyd96s33kmy8wlck903m0srkkndeaawqrqfzek --encrypted-regex "PASSWORD|EMAIL|TOKEN" hatshop-secrets.dec.yaml > hatshop-secrets.enc.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hatshop-secrets
    labels:
        app.kubernetes.io/name: hatshop
        app.kubernetes.io/instance: prod
        app.kubernetes.io/component: secrets
spec:
    secretTemplates:
        - name: hatshop-secrets
          labels:
            app.kubernetes.io/name: hatshop
            app.kubernetes.io/instance: prod
            app.kubernetes.io/component: secrets
          stringData:
            # Neon Database Password
            HATSHOP_DB_PASSWORD: ENC[AES256_GCM,data:oIaqRvahtGnrrzDF,iv:JmN09Gmq9AhmjdxVg+esqwWpDVBa42Rx3B5STHjMG0U=,tag:ypnIut5bC9yoedXXrHEPHQ==,type:str]
            # Admin Configuration (Chapter 7)
            HATSHOP_ADMIN_USERNAME: hatshopadmin
            HATSHOP_ADMIN_PASSWORD: ENC[AES256_GCM,data:bmMINS2JgNMneo2Q,iv:rIfLn5G/ttCTLDbmyIv8Dbx4Xlk8kmrfko4c7klg6Hw=,tag:T315ZDRdaA7EsNFL81JVkA==,type:str]
            # PayPal Configuration (Chapter 6) - sensitive fields
            HATSHOP_PAYPAL_EMAIL: ENC[AES256_GCM,data:OYlHDEWldkEeJoGA8RvNL5LUv2MskLysphBD2W2s7XgoxA==,iv:EEDR9FVb+jQ8LtBtc5bpIbiWtBdXMpoDIgVOcgQoPl4=,tag:S96QHMD5Az2Z+u1QUSoDrA==,type:str]
            HATSHOP_PAYPAL_RETURN_URL: https://hatshop.renewed-renaissance.com/prod/paypal_return.php
            HATSHOP_PAYPAL_CANCEL_URL: https://hatshop.renewed-renaissance.com/prod/paypal_cancel.php
            HATSHOP_PAYPAL_IPN_URL: https://hatshop.renewed-renaissance.com/prod/paypal_ipn.php
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mg4zlx7p736nnrp7glt7gyd96s33kmy8wlck903m0srkkndeaawqrqfzek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SkRUS3FUaU9RT2pmRWlN
            Vy9rdzJ3WTZJR2pvQnAxL0ptWEs5ZlIzT1c4CmRBVldsWElsTGxwMlZWVzQ0QnB0
            dzMzbzlsbWkrVXZ2UXhaSzZrTFhrL0EKLS0tIEtmdmpwTTZrR3U2dzNNS2FIcTJG
            cWxqWWVkb1A0aVA1ZVBWUFlHdDV0OTgK8ZN86dZQ3VHQcC4aUN0feRX/IVvAMC27
            GM6721TYwrPnSNZ1pzHqcgvAATwLgSDjiQgJLxfouMzvpMJzu0H4wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T04:08:37Z"
    mac: ENC[AES256_GCM,data:q7MtMCBapLi94avEgAZt0HvQfgXPYmVm/WZiCanKzPbmtj60rqstZS+dk1qLJ9LlprTo4T+OWhfhBJzO1rzhtYxQLfts0DLzrVx95MJACnXkd+exXopHuK8ty61Xwn+C0JeuMvuzHBsKzwS+bSjJFZExYk/rAVeC4CsEQfHySMc=,iv:463U3RxPTLf+6cATAvrzGLT3aIuHGXDxLajya63EanM=,tag:kPHIhreZEYeyG1m1BjUkww==,type:str]
    pgp: []
    encrypted_regex: PASSWORD|EMAIL|TOKEN
    version: 3.9.3
