# HatShop Secrets - SOPS encrypted
# Encrypt with: sops encrypt --age age1mg4zlx7p736nnrp7glt7gyd96s33kmy8wlck903m0srkkndeaawqrqfzek --encrypted-regex "PASSWORD|EMAIL|TOKEN" hatshop-secrets.dec.yaml > hatshop-secrets.enc.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hatshop-secrets
    labels:
        app.kubernetes.io/name: hatshop
        app.kubernetes.io/instance: prod
        app.kubernetes.io/component: secrets
spec:
    secretTemplates:
        - name: hatshop-secrets
          labels:
            app.kubernetes.io/name: hatshop
            app.kubernetes.io/instance: prod
            app.kubernetes.io/component: secrets
          stringData:
            # Neon Database Password
            HATSHOP_DB_PASSWORD: ENC[AES256_GCM,data:5dVJWxAwYTBxoHje,iv:TBlMdaE/O2uqamX2/Vsudp1bZexLEGPeTspCf+MV+lU=,tag:So/RhYWA69lB4FJXaRUKxg==,type:str]
            # Admin Configuration (Chapter 7)
            HATSHOP_ADMIN_USERNAME: hatshopadmin
            HATSHOP_ADMIN_PASSWORD: ENC[AES256_GCM,data:hBy/tqPLHKisH8Bo,iv:CAHMhuFRtWUghot3mylJVyvj/bqrYOu2fsRUZT8ffI4=,tag:ZRMiMAsW6scq/4kRQQaeDg==,type:str]
            # PayPal Configuration (Chapter 6) - sensitive fields
            HATSHOP_PAYPAL_EMAIL: ENC[AES256_GCM,data:xJ2Pc2wzBvmAhh9UYanla2hu3Hhnho+tWvHlGBSu+A0Oxg==,iv:fARou0oyIgxWOKJdd7KWNWl5SRMo6nEn8BRhNk7Ri4Y=,tag:y0moEei2SwslhVjfPkqcMg==,type:str]
            HATSHOP_PAYPAL_RETURN_URL: https://hatshop.renewed-renaissance.com/prod/paypal_return.php
            HATSHOP_PAYPAL_CANCEL_URL: https://hatshop.renewed-renaissance.com/prod/paypal_cancel.php
            HATSHOP_PAYPAL_IPN_URL: https://hatshop.renewed-renaissance.com/prod/paypal_ipn.php
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mg4zlx7p736nnrp7glt7gyd96s33kmy8wlck903m0srkkndeaawqrqfzek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdUs5b1dZOEl4YWNLelpH
            QVMyR0l3dXIzTGd1UzJvY3lQSzNkVmhhZG4wClVobSt3VlRHalhOMkRNZ3BGc3or
            YTdjRUFxSzNhYlJJYkhjbldrdEJqT0kKLS0tIEliNmVSNURRWnc3YXBaQlp1TGFV
            YUtNd00ySUdVVVFQZ2YxbUVUbHc4ZG8K4mWQExgkHPCOwBTrWVfh1hpnRKvR2JV3
            qZMhi3ySQAbIwR6EyVF+xuNhcBUYic/OR2POi0B1FvkukG1Wclji2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T20:32:47Z"
    mac: ENC[AES256_GCM,data:TNZEekcSuKR3jb5hUGtJ+f+ouUXl+M99eFzotJiTDxxdil3cIfvEaY5iotNH+0dOvbDmgvaj2WsBH6xMeHIdN3oEvCl1J62IsdF3v/cA13jFvBhiy1OjkOUEoIITd0sAwNl28/ap6DW0/U4Usfbf3xCWEt9l31FLvH9wmA+IU/I=,iv:r6X0dWjXDKV4+HwFaDSVCNNYbPnFVifrICcKs6jDVJY=,tag:p42Il2Wpg05hSzhTPOy3PQ==,type:str]
    pgp: []
    encrypted_regex: PASSWORD|EMAIL|TOKEN
    version: 3.9.3
