# HatShop Secrets - SOPS encrypted
# Encrypt with: sops encrypt --age age1mg4zlx7p736nnrp7glt7gyd96s33kmy8wlck903m0srkkndeaawqrqfzek --encrypted-regex "PASSWORD|EMAIL|TOKEN" hatshop-secrets.dec.yaml > hatshop-secrets.enc.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hatshop-secrets
    labels:
        app.kubernetes.io/name: hatshop
        app.kubernetes.io/instance: stage
        app.kubernetes.io/component: secrets
spec:
    secretTemplates:
        - name: hatshop-secrets
          labels:
            app.kubernetes.io/name: hatshop
            app.kubernetes.io/instance: stage
            app.kubernetes.io/component: secrets
          stringData:
            # Database Password
            HATSHOP_DB_PASSWORD: ENC[AES256_GCM,data:fBPYTBuxCbg=,iv:TFflVHd1yvU2XmDnkLXoK/c2bCAsf/c5SeJitYcqlFM=,tag:g53DQJfPdnUvNVEC5EGi1w==,type:str]
            # Admin Configuration (Chapter 7)
            HATSHOP_ADMIN_USERNAME: hatshopadmin
            HATSHOP_ADMIN_PASSWORD: ENC[AES256_GCM,data:3EPc88xsotq0UbGl,iv:5tmSiipUZBMQWtygqa1SEwazkb3JsyPZF447nWUetak=,tag:kP3fKxMEsOtXnIQFXeD74w==,type:str]
            # PayPal Configuration (Chapter 6) - sensitive fields
            HATSHOP_PAYPAL_EMAIL: ENC[AES256_GCM,data:K8XaGkm6T8c7FoXyzuEQVEwlWV32STlOhfVRSQYaXA==,iv:EHD09qFpx4X8IYWdYH1qZe1I8288e3JxkthiI3GgG0E=,tag:oIG1uLseXbutvnJ3aYDqyw==,type:str]
            HATSHOP_PAYPAL_RETURN_URL: http://localhost/paypal_return.php
            HATSHOP_PAYPAL_CANCEL_URL: http://localhost/paypal_cancel.php
            HATSHOP_PAYPAL_IPN_URL: http://localhost/paypal_ipn.php
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mg4zlx7p736nnrp7glt7gyd96s33kmy8wlck903m0srkkndeaawqrqfzek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhazh4a3BMS21wUDFzOFJH
            Y3k3WURKMzhBWUptN0VBZlU0UHpiZzYxWmhJCkxrUEtuUjhHdzR4RFpKanBKWGhI
            cCtXNld5SnBJTUgxMlI5RDYvS3FZcmMKLS0tIFFOM1BVa09mVktqSkhDcGNLdmlO
            a01Wc2RiaStXODJsT0ljU0xoakdBcE0Kx1WQ4iKtD1kkAll71Inn1IOy+O9gL6cp
            eyBcZ3fIjw1EbFeFKujpe3LGjIiq/CVmZ7qfBM0Pf7L1s/MLP4MXyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T16:08:03Z"
    mac: ENC[AES256_GCM,data:MBO26JwGoofZSEEQ30+Cw9doLrSjafDJB3NxesJir/8DG58xJsOixBhaR2FuIEuC7LYL+MEOErMkX2kVB7HegfYdEwR0/JBTDdNZ6w8x+hvJtyhmSVgABUq/yauohJM6Tv7wIKITv0xjT8nvXrGCCjwxk/5ZfyBMEx9nRS7eFFM=,iv:OEJ5Ey4z84lJ24vbtmVVv1IV3kZ8AzysfOsAdThtx6g=,tag:4xZYY4DwqADnsCGouJOcjg==,type:str]
    pgp: []
    encrypted_regex: PASSWORD|EMAIL
    version: 3.9.3
