apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx-service-account
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          ports:
            - containerPort: {{ (index .Values.nginx.ports 0).containerPort }}
          volumeMounts:
            {{- range .Values.nginx.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: nginx-env-config
          resources:
            limits:
              memory: {{ .Values.nginx.resources.limits.memory }}
              cpu: {{ .Values.nginx.resources.limits.cpu }}
              ephemeral-storage: {{ .Values.nginx.resources.limits.ephemeral-storage }}
            requests:
              memory: {{ .Values.nginx.resources.requests.memory }}
              cpu: {{ .Values.nginx.resources.requests.cpu }}
              ephemeral-storage: {{ .Values.nginx.resources.requests.ephemeral-storage }}
      volumes:
        - name: code-volume
          hostPath:
            path: {{ .Values.volumes.codeVolume.path }}
        - name: nginx-config-volume
          hostPath:
            path: {{ .Values.volumes.nginxConfigVolume.path }}
        - name: ssl-cert-volume
          hostPath:
            path: {{ .Values.volumes.sslCertVolume.path }}
        - name: ssl-key-volume
          hostPath:
            path: {{ .Values.volumes.sslKeyVolume.path }}
